#!/usr/bin/env bash

# Update the system and install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Create a custom HTML file for redirection
echo '<html><head><meta http-equiv="refresh" content="0;URL=https://www.youtube.com/watch?v=QH2-TGUlwu4"></head></html>' | sudo tee /var/www/html/redirect_me.html

# Configure the Nginx server block for redirection
sudo tee /etc/nginx/sites-available/redirect_me <<EOF
server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        root /var/www/html;
        index index.html;
    }
}
EOF

# Create a symbolic link to enable the configuration
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Remove the default Nginx default site if needed
sudo rm /etc/nginx/sites-enabled/default

# Test Nginx configuration and restart the server
sudo nginx -t
sudo service nginx restart
