#!/usr/bin/env bash
# Script that generates a MySQL dump and creates a
# compressed archive out of it.
file_n='backup.sql'
v_date=$(date +'%d-%m-%Y')
sudo mysqldump -u root -p"$1" --all-databases > "$file_n"
tar -czvf "$v_date.tar.gz" "$file_n"
