#!/usr/bin/env bash
# script that sets the listen port to 80
sudo sed -i "s/8080/80/g" /etc/nginx/sites-available/default
# delete the default file
sudo rm -f /etc/nginx/sites-enabled/default
# create a symbolic link
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
# script that restarts nginx
sudo service nginx restart
