#!/usr/bin/env bash
# script that sets the listen port to 80 in the file /etc/nginx/sites-enabled/default
sudo sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
# script that restarts nginx
sudo service nginx restart
