#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.

# use IFS to separate the fields
while IFS=: read -r USERNAME _ USER_ID GROUP_ID USER_ID_INFO HOME_DIRECTORY COMMAND_SHELL PASSWORD _;
do
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here:"

done < "/etc/passwd"