#!/bin/env bash
# Get the Apache log file
logfile=apache-access.log
# Use awk to extract the IP address and HTTP status code and format them as a list
awk '{print $1, $9}' "$logfile" | awk '{printf "%s %s\n", $1, $2}'