#!/bin/bash
# Get the Apache log file
logfile=apache-access.log
# Use awk to extract the IP address and HTTP status code and store them in separate lines
IP_HTTP_CODE=$(awk '{print $1,$9}' $logfile)
# Convert to a list using IFS and read
IFS=$'\n'
read -d '' -ra IP_HTTP_CODE_LIST <<< "$IP_HTTP_CODE"
# Print the IP address and HTTP status code in a list format
printf '%s\n' "${IP_HTTP_CODE_LIST[@]}"