#!/usr/bin/env bash
# Displays "Best School" 10 times using while loop.
# The ninth line is hi.
 i=1
while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    i=$((i + 1))
done
