#!/usr/bin/env bash
# Bash script to display the content of the current directory in a list format,
# showing only the part of the name after the first dash

for i in *
do
    echo "$i" | cut -d'-' -f2
done