#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
# back up the original file
cp /etc/hosts ~/hosts.new
sed -i 's/.*localhost/127.0.0.2 localhost/g' ~/hosts.new
sed -i 's/.*facebook.com/8.8.8.8 facebook.com/g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
