#!/usr/bin/env bash

# Stop the Nginx service
service nginx stop

# Create a backup of the Nginx configuration file
sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.backup

# Change the user under which Nginx runs to 'nginx'
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Update the Nginx configuration to listen on all active IPs on port 8080
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default

# Restart the Nginx service
service nginx start
